alias: "[Light] [FP2] : [Server Room] : [Motion Cleared] : [Lights Off]"
description: ""
triggers:
  - trigger: template
    value_template: |
      {{
        is_state('binary_sensor.basement_server_inovelli_presence_occupancy', 'off')
        and is_state('binary_sensor.basement_server_room_aqara_fp2_03_presence_sensor', 'off')
      }}
    for:
      hours: 0
      minutes: 2
      seconds: 0
conditions: []
actions:
  - action: light.turn_off
    target:
      entity_id: light.basement_server_inovelli_presence
mode: single
