alias: "[Light] [ZSE11] : [Concessions] : [Motion Cleared] : [Lights Off]"
description: ""
triggers:
  - trigger: template
    value_template: |
      {{
        is_state('binary_sensor.basement_concessions_qsensor_motion_detection', 'off')
        and is_state('binary_sensor.basement_concessions_inovelli_presence_occupancy', 'off')
      }}
    for: "00:02:00"
conditions: []
actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.basement_concessions_lights
mode: single
