alias: "[Light] [inovelli] : [Primary Bathroom] : [Fan Light] : [Sync Shower]"
description: ""
triggers:
  - trigger: state
    entity_id: light.upstairs_primary_bath_fan_light_inovelli_on_off
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state is not none and trigger.to_state.state == 'on' }}"
          - condition: state
            entity_id: light.upstairs_primary_bath_shower_inovelli_presence
            state: "off"
        sequence:
          - action: light.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: light.upstairs_primary_bath_shower_inovelli_presence
          - action: input_boolean.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: input_boolean.upstairs_primary_bathroom_use_shower_delay
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state is not none and trigger.to_state.state == 'off' }}"
          - condition: state
            entity_id: light.upstairs_primary_bath_shower_inovelli_presence
            state: "on"
        sequence:
          - action: light.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: light.upstairs_primary_bath_shower_inovelli_presence
    default: []
mode: restart

