alias: "[Light] [ZSE11] : [Basement Hallway] : [Motion Cleared] : [Lights Off]"
description: ""
triggers:
  - trigger: template
    value_template: |
      {{
        is_state('binary_sensor.basement_hallway_qsensor_motion_detection', 'off')
        and is_state('binary_sensor.basement_hallway_inovelli_presence_occupancy', 'off')
      }}
    for: "00:02:00"
conditions: []
actions:
  - action: light.turn_off
    metadata: {}
    target:
      entity_id: light.basement_hall_lights
    data: {}
mode: single
