alias: "[Light] [Inovelli] : [Movie Room] : [Motion Cleared] : [Lights Off]"
description: >
  Movie room is OFF-only: we don't auto-turn on lights here; we only ensure
  lights turn off after the room is empty.
triggers:
  - trigger: template
    value_template: |
      {{
        is_state('binary_sensor.basement_movie_inovelli_presence_occupancy', 'off')
        and is_state('binary_sensor.basement_rumpus_room_aqara_fp2_01_presence_sensor', 'off')
      }}
conditions: []
actions:
  - delay: >-
      {% set raw = states('input_select.basement_movie_room_occupancy_off_delay') %}
      {% set d = raw | replace('"','') | replace("'","") | trim %}
      {{ d if d not in ['unknown','unavailable',''] else '00:05:00' }}
  - condition: template
    value_template: |
      {{
        is_state('binary_sensor.basement_movie_inovelli_presence_occupancy', 'off')
        and is_state('binary_sensor.basement_rumpus_room_aqara_fp2_01_presence_sensor', 'off')
      }}
  - action: light.turn_off
    target:
      entity_id:
        - light.basement_movie_room_lights
        - light.basement_movie_room_ambient_lighting
mode: restart
