alias: "[Light] [FP2] : [Rumpus Room] : [Motion Cleared] : [Lights Off]"
triggers:
  - trigger: template
    value_template: |
      {{
        is_state('binary_sensor.basement_rumpus_room_aqara_fp2_01_presence_sensor', 'off')
        and is_state('binary_sensor.basement_rumpus_room_aqara_fp2_02_presence_sensor', 'off')
        and is_state('binary_sensor.basement_rumpus_aqara_fp300_presence_presence', 'off')
        and is_state('binary_sensor.basement_rumpus_room_inovelli_presence_occupancy', 'off')
      }}
    for: "00:05:00"
conditions: []
actions:
  - action: light.turn_off
    target:
      entity_id: light.basement_rumpus_room_lights
  - action: light.turn_off
    target:
      entity_id: light.basement_rumpus_room_lamp
mode: single
