alias: "[Light] [ZSE11] : [Concessions] : [Motion Cleared] : [Lights Off]"
description: ""
triggers:
  - trigger: template
    value_template: |
      {{
        is_state('binary_sensor.basement_concessions_qsensor_motion_detection', 'off')
        and is_state('binary_sensor.basement_concessions_inovelli_presence_occupancy', 'off')
      }}
conditions: []
actions:
  - condition: template
    value_template: |
      {# Only run when hold is clear #}
      {% set s = 'basement_concessions_inovelli_presence' %}
      {% set manual = states('input_text.inovelli_manual_hold') | int(85) %}
      {% set auto = states('input_text.inovelli_auto_hold') | int(0) %}
      {% set led1 = states('number.' ~ s ~ '_defaultled1colorwhenon') | int(-1) %}
      {{ led1 != manual and led1 != auto }}
  - delay: >-
      {% set raw = states('input_select.basement_concessions_occupancy_off_delay') %}
      {% set d = raw | replace('"','') | replace("'","") | trim %}
      {{ d if d not in ['unknown','unavailable',''] else '00:02:00' }}
  - condition: template
    value_template: |
      {{
        is_state('binary_sensor.basement_concessions_qsensor_motion_detection', 'off')
        and is_state('binary_sensor.basement_concessions_inovelli_presence_occupancy', 'off')
      }}
  - condition: template
    value_template: |
      {# Re-check hold state after the delay #}
      {% set s = 'basement_concessions_inovelli_presence' %}
      {% set manual = states('input_text.inovelli_manual_hold') | int(85) %}
      {% set auto = states('input_text.inovelli_auto_hold') | int(0) %}
      {% set led1 = states('number.' ~ s ~ '_defaultled1colorwhenon') | int(-1) %}
      {{ led1 != manual and led1 != auto }}
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.basement_concessions_lights
mode: restart
