alias: "[Light] [FP2] : [Rumpus Room] : [Motion Detected] : [Lights On]"
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.basement_rumpus_room_aqara_fp2_01_presence_sensor
      - binary_sensor.basement_rumpus_room_aqara_fp2_02_presence_sensor
      - binary_sensor.basement_rumpus_aqara_fp300_presence_presence
      - binary_sensor.basement_rumpus_room_inovelli_presence_occupancy
    from: null
    to: "on"
conditions: []
actions:
  - action: light.turn_on
    metadata: {}
    target:
      entity_id: light.basement_rumpus_room_lights
    data: {}
  - action: light.turn_on
    metadata: {}
    target:
      entity_id: light.basement_rumpus_room_lamp
    data: {}
mode: single
