"""VestaboardAutomation mixin — base for automation apps that register with the controller."""

from __future__ import annotations

import random
import time
import uuid
from abc import abstractmethod
from typing import Any, Optional


class VestaboardAutomation:
    """Mixin for Vestaboard automation apps.

    Usage::

        class CalendarClockApp(hass.Hass, VestaboardAutomation):
            automation_type = "calendar_clock"
            display_name = "Calendar Clock"
            ...

    The mixin provides:
    - ``register_with_controller()`` / ``deregister_from_controller()`` for lifecycle.
    - ``push_frame()`` to send frames to the controller's queue.
    - Random-interval scheduling helpers.
    - Abstract ``generate_frame()`` that subclasses must implement.

    Subclasses must call ``register_with_controller()`` from ``initialize()``
    and ``deregister_from_controller()`` from ``terminate()``.
    """

    # ------------------------------------------------------------------
    # Class-level metadata (subclasses override)
    # ------------------------------------------------------------------

    #: Machine-readable type identifier (e.g. "calendar_clock").
    automation_type: str = ""

    #: Human-readable name shown in status / logs.
    display_name: str = "Automation"

    #: Short description shown in the store UI.
    display_description: str = "A Vestaboard automation."

    #: Default TTL in seconds for frames generated by this automation.
    default_ttl_s: Optional[int] = None

    #: Default max age in seconds from frame creation time.
    default_max_age_s: Optional[int] = None

    #: Whether frames from this automation should expire by default.
    default_should_expire: bool = False

    #: Default UI-editable configuration for this automation.
    DEFAULT_UI_CONFIG: dict[str, Any] = {}

    # ------------------------------------------------------------------
    # Registration with controller
    # ------------------------------------------------------------------

    _controller: Any = None
    _registration_retries: int = 0
    _max_registration_retries: int = 10

    def register_with_controller(self) -> None:
        """Find the controller app via get_app() and register this automation.

        Retries with exponential backoff if the controller isn't ready yet.
        Call this from ``initialize()``.
        """
        controller_name = self.args.get("controller_app", "vestaboard_controller")
        controller = self.get_app(controller_name)

        if controller is None:
            self._registration_retries += 1
            if self._registration_retries > self._max_registration_retries:
                self.log(
                    f"Failed to find controller {controller_name!r} after "
                    f"{self._max_registration_retries} retries — giving up",
                    level="ERROR",
                )
                return
            delay = min(2 ** self._registration_retries, 30)
            self.log(
                f"Controller {controller_name!r} not ready — "
                f"retry {self._registration_retries}/{self._max_registration_retries} "
                f"in {delay}s",
                level="WARNING",
            )
            self.run_in(self._retry_registration, delay)
            return

        self._controller = controller
        self._registration_retries = 0

        # The automation_id is the AppDaemon app key (self.name)
        controller.register_automation(self)
        self.log(
            f"Registered with controller {controller_name!r} as {self.name!r}",
            level="INFO",
        )

        # Apply any persisted config the controller pushed back during registration
        self._apply_initial_config()

    def _retry_registration(self, kwargs: dict) -> None:
        """Retry callback for register_with_controller."""
        self.register_with_controller()

    def _apply_initial_config(self) -> None:
        """Apply config values that the controller may have pushed during registration.

        Subclasses can override for custom config handling.
        """
        pass

    def deregister_from_controller(self) -> None:
        """Deregister this automation from the controller.

        Call this from ``terminate()``.
        """
        if self._controller is not None:
            try:
                self._controller.deregister_automation(self.name)
                self.log(
                    f"Deregistered from controller as {self.name!r}",
                    level="INFO",
                )
            except Exception as exc:
                self.log(
                    f"Failed to deregister from controller: {exc!r}",
                    level="WARNING",
                )
            self._controller = None

    # ------------------------------------------------------------------
    # Frame pushing
    # ------------------------------------------------------------------

    def push_frame(
        self,
        grid: list[list[int]],
        ttl_s: Optional[int] = None,
        max_age_s: Optional[int] = None,
        override_ttl: bool = False,
        should_expire: bool = False,
    ) -> None:
        """Push a frame to the controller's queue.

        Args:
            grid: 6x22 character grid.
            ttl_s: TTL in seconds (None = use default).
            max_age_s: Max age from creation (None = use default).
            override_ttl: Immediately display, bypassing active TTL.
            should_expire: Drop frame after TTL instead of moving to fallback.
        """
        if self._controller is None:
            self.log(
                "Cannot push frame — not registered with controller",
                level="WARNING",
            )
            return

        self._controller.push_automation_frame(
            automation_id=self.name,
            source_label=self.display_name,
            grid=grid,
            ttl_s=ttl_s,
            max_age_s=max_age_s,
            override_ttl=override_ttl,
            should_expire=should_expire,
        )

    # ------------------------------------------------------------------
    # Config helpers
    # ------------------------------------------------------------------

    def get_effective_config(self) -> dict[str, Any]:
        """Return merged YAML args + UI config for status publishing."""
        cfg = dict(self.args or {})
        # Remove internal AppDaemon keys
        for key in ("module", "class", "dependencies", "controller_app"):
            cfg.pop(key, None)
        return cfg

    def get_resolved_ttl_s(self) -> Optional[int]:
        """Resolve TTL from config, falling back to class default."""
        cfg = self.args or {}
        ttl_minutes = cfg.get("ttl_minutes")
        if ttl_minutes is not None:
            return int(float(ttl_minutes) * 60)
        return self.default_ttl_s

    def get_resolved_should_expire(self) -> bool:
        """Resolve should_expire from config, falling back to class default."""
        cfg = self.args or {}
        return bool(cfg.get("should_expire", self.default_should_expire))

    # ------------------------------------------------------------------
    # Config schema & preview (subclasses override)
    # ------------------------------------------------------------------

    @classmethod
    def get_config_schema(cls) -> dict[str, Any]:
        """Return UI-renderable config field definitions."""
        return {}

    def get_preview_frame(self) -> list[list[int]]:
        """Return a representative 6x22 frame for preview display."""
        return [[0] * 22 for _ in range(6)]

    # ------------------------------------------------------------------
    # UI config updates from controller
    # ------------------------------------------------------------------

    def on_config_updated(self, config: dict[str, Any]) -> None:
        """Called by controller when UI config changes.

        Merges new values into self.args so automation code can read them.
        Subclasses can override for side-effects (e.g. rescheduling timers).
        """
        if not isinstance(self.args, dict):
            return
        self.args.update(config)

    def set_enabled(self, enabled: bool) -> None:
        """Called by controller to enable/disable this automation.

        Subclasses should override to start/stop their timers.
        """
        pass

    # ------------------------------------------------------------------
    # Abstract interface
    # ------------------------------------------------------------------

    @abstractmethod
    async def generate_frame(self, **kwargs) -> list[list[int]]:
        """Generate a 6x22 character grid for the current moment."""
        raise NotImplementedError

    # ------------------------------------------------------------------
    # Random interval scheduling helpers
    # ------------------------------------------------------------------

    _random_interval_handle: Any = None
    _next_fire_time: Optional[float] = None

    def _schedule_random_interval(
        self,
        callback,
        min_minutes: float = 30,
        max_minutes: float = 120,
    ) -> None:
        """Schedule a callback at a random interval within the given range.

        After the callback fires, call this again to schedule the next one.
        """
        self._cancel_random_interval()

        min_minutes = min(min_minutes, max_minutes)
        delay_s = random.uniform(float(min_minutes), float(max_minutes)) * 60
        self._next_fire_time = time.time() + delay_s

        self._random_interval_handle = self.run_in(callback, int(delay_s))

        self.log(
            f"Random interval scheduled: next fire in {delay_s / 60:.1f} min",
            level="DEBUG",
        )

    def _cancel_random_interval(self) -> None:
        """Cancel any pending random interval timer."""
        if self._random_interval_handle is not None:
            try:
                self.cancel_timer(self._random_interval_handle)
            except Exception:
                pass
            self._random_interval_handle = None
        self._next_fire_time = None

    # ------------------------------------------------------------------
    # Helpers for fire-and-push pattern
    # ------------------------------------------------------------------

    async def _generate_and_push(self, **generate_kwargs) -> None:
        """Generate a frame and push it to the controller."""
        try:
            grid = await self.generate_frame(**generate_kwargs)
            if grid and any(any(cell != 0 for cell in row) for row in grid):
                self.push_frame(
                    grid,
                    ttl_s=self.get_resolved_ttl_s(),
                    max_age_s=self.default_max_age_s,
                    should_expire=self.get_resolved_should_expire(),
                )
            else:
                self.log("generate_frame returned blank grid — skipping push", level="DEBUG")
        except Exception as exc:
            self.log(f"generate_and_push failed: {exc!r}", level="ERROR")
