"""VestaboardAutomation mixin — base for automation apps that register with the controller."""

from __future__ import annotations

import json
import random
import time
import uuid
from abc import abstractmethod
from typing import Any, Optional


class VestaboardAutomation:
    """Mixin for Vestaboard automation apps.

    Usage::

        class CalendarClockApp(hass.Hass, VestaboardAutomation):
            automation_type = "calendar_clock"
            display_name = "Calendar Clock"
            ...

    The mixin provides:
    - ``register_with_controller()`` / ``deregister_from_controller()`` for lifecycle.
    - ``push_frame()`` to send frames to the controller's queue.
    - Random-interval scheduling helpers.
    - Abstract ``generate_frame()`` that subclasses must implement.

    Subclasses must call ``register_with_controller()`` from ``initialize()``
    and ``deregister_from_controller()`` from ``terminate()``.

    Communication with the controller is entirely event-based — no direct
    ``get_app()`` references.  The mixin fires ``vestaboard_controller_command``
    events and listens for per-automation events fired back by the controller.
    """

    # ------------------------------------------------------------------
    # Class-level metadata (subclasses override)
    # ------------------------------------------------------------------

    #: Machine-readable type identifier (e.g. "calendar_clock").
    automation_type: str = ""

    #: Human-readable name shown in status / logs.
    display_name: str = "Automation"

    #: Short description shown in the store UI.
    display_description: str = "A Vestaboard automation."

    #: Default TTL in seconds for frames generated by this automation.
    default_ttl_s: Optional[int] = None

    #: Default max age in seconds from frame creation time.
    default_max_age_s: Optional[int] = None

    #: Whether frames from this automation should expire by default.
    default_should_expire: bool = False

    #: Default UI-editable configuration for this automation.
    DEFAULT_UI_CONFIG: dict[str, Any] = {}

    # ------------------------------------------------------------------
    # Registration with controller
    # ------------------------------------------------------------------

    # Listener handles for controller events
    _event_handles: list = []

    def register_with_controller(self) -> None:
        """Register with the controller via HA event system.

        Fires a ``vestaboard_controller_command`` event with command
        ``register_automation``.  The controller responds by firing back a
        config event.  Also sets up listeners for config/enabled/generate
        events scoped to this automation, and a listener for the
        ``vestaboard_controller_ready`` event so re-registration happens
        automatically after a controller restart.

        Call this from ``initialize()``.
        """
        self._event_handles = []
        self._preview_overrides = None

        # Listen for controller→automation events (shared event names, filter by automation_id)
        handle = self.listen_event(self._on_config_event, "vb_auto_config")
        self._event_handles.append(handle)

        handle = self.listen_event(self._on_enabled_event, "vb_auto_enabled")
        self._event_handles.append(handle)

        handle = self.listen_event(self._on_generate_event, "vb_auto_generate")
        self._event_handles.append(handle)

        # Re-register if controller restarts
        handle = self.listen_event(
            self._on_controller_ready,
            "vestaboard_controller_ready",
        )
        self._event_handles.append(handle)

        # Fire registration event to controller
        self._fire_register_event()

        self.log(
            f"Registered with controller via events as {self.name!r}",
            level="INFO",
        )

    def _fire_register_event(self) -> None:
        """Fire the register_automation command to the controller."""
        payload = {
            "automation_id": self.name,
            "automation_type": self.automation_type,
            "display_name": self.display_name,
            "display_description": self.display_description,
            "default_ttl_s": self.default_ttl_s,
            "default_max_age_s": self.default_max_age_s,
            "default_should_expire": self.default_should_expire,
            "DEFAULT_UI_CONFIG": self.DEFAULT_UI_CONFIG,
            "config_schema": self.get_config_schema(),
            "preview_frame": json.dumps(self.get_preview_frame()),
        }
        self.fire_event(
            "vestaboard_controller_command",
            command="register_automation",
            payload=json.dumps(payload),
        )

    def deregister_from_controller(self) -> None:
        """Deregister this automation from the controller.

        Fires a ``vestaboard_controller_command`` event with command
        ``deregister_automation`` and cancels all event listeners.

        Call this from ``terminate()``.
        """
        try:
            self.fire_event(
                "vestaboard_controller_command",
                command="deregister_automation",
                payload=json.dumps({"automation_id": self.name}),
            )
            self.log(
                f"Deregistered from controller as {self.name!r}",
                level="INFO",
            )
        except Exception as exc:
            self.log(
                f"Failed to fire deregister event: {exc!r}",
                level="WARNING",
            )

        # Cancel all controller event listeners
        for handle in self._event_handles:
            try:
                self.cancel_listen_event(handle)
            except Exception:
                pass
        self._event_handles = []

    # ------------------------------------------------------------------
    # Controller event handlers
    # ------------------------------------------------------------------

    def _on_config_event(self, event_name: str, data: dict, kwargs: dict) -> None:
        """Handle a config update event from the controller."""
        target = data.get("automation_id")
        if target != self.name:
            return
        config = data.get("config", {})
        if not isinstance(config, dict):
            try:
                config = json.loads(config)
            except Exception:
                config = {}
        # Log effective config (defaults merged with stored) so all values
        # are visible, even keys never explicitly stored in the config file.
        effective = {**self.DEFAULT_UI_CONFIG, **config}
        config_summary = " | ".join(f"{k}={v!r}" for k, v in effective.items())
        self.log(
            f"Config event received: {config_summary}",
            level="INFO",
        )
        self.on_config_updated(config)

    def _on_enabled_event(self, event_name: str, data: dict, kwargs: dict) -> None:
        """Handle an enabled/disabled event from the controller."""
        if data.get("automation_id") != self.name:
            return
        enabled = bool(data.get("enabled", True))
        self.log(
            f"Enabled event received: enabled={enabled}",
            level="INFO",
        )
        self.set_enabled(enabled)

    def _on_generate_event(self, event_name: str, data: dict, kwargs: dict) -> None:
        """Handle a generate request from the controller."""
        target = data.get("automation_id")
        if target != self.name:
            return
        self.log(
            f"Generate event received: automation_id={target!r} data_keys={list(data.keys())}",
            level="INFO",
        )
        generate_kwargs = data.get("generate_kwargs", {})
        if not isinstance(generate_kwargs, dict):
            try:
                generate_kwargs = json.loads(generate_kwargs)
            except Exception:
                generate_kwargs = {}
        preview_only = bool(data.get("preview_only", False))
        self.create_task(self._handle_generate_request(generate_kwargs, preview_only))

    def _on_controller_ready(self, event_name: str, data: dict, kwargs: dict) -> None:
        """Re-register when the controller announces it has restarted."""
        self.log(
            f"Controller ready event — re-registering {self.name!r}",
            level="INFO",
        )
        # Re-fire the registration event (listeners already set up)
        self._fire_register_event()

    # ------------------------------------------------------------------
    # Generate request handler (called by _on_generate_event)
    # ------------------------------------------------------------------

    async def _handle_generate_request(
        self, generate_kwargs: dict, preview_only: bool
    ) -> None:
        """Generate a frame and either push it or return it as a preview.

        Args:
            generate_kwargs: Keyword arguments passed to ``generate_frame()``.
            preview_only: If True, fire a ``push_ai_art_preview_result`` event
                instead of pushing to the queue.
        """
        # Set instance-level preview overrides so that automations which
        # call push_frame() directly from generate_frame() (e.g. calendar_summary)
        # also get the short TTL + override behaviour.
        preview_short = bool(generate_kwargs.get("_preview_short_ttl", False))
        override_ttl = bool(generate_kwargs.get("override_ttl", True))
        if preview_short:
            self._preview_overrides = {
                "ttl_s": 30,
                "override_ttl": True,
                "should_expire": True,
            }
        elif override_ttl:
            self._preview_overrides = {"override_ttl": True}
        else:
            self._preview_overrides = None

        # Strip internal keys before passing to generate_frame()
        frame_kwargs = {
            k: v for k, v in generate_kwargs.items()
            if k not in ("override_ttl", "_preview_short_ttl")
        }
        try:
            grid = await self.generate_frame(**frame_kwargs)
        except Exception as exc:
            self.log(f"generate_frame failed: {exc!r}", level="ERROR")
            return
        finally:
            self._preview_overrides = None

        if preview_only:
            subject = generate_kwargs.get("subject", "abstract art")
            self.fire_event(
                "vestaboard_controller_command",
                command="push_ai_art_preview_result",
                payload=json.dumps({
                    "characters": json.dumps(grid),
                    "subject": subject,
                }),
            )
        else:
            if grid and any(any(cell != 0 for cell in row) for row in grid):
                self.push_frame(
                    grid,
                    ttl_s=30 if preview_short else self.get_resolved_ttl_s(),
                    max_age_s=self.default_max_age_s,
                    override_ttl=override_ttl,
                    should_expire=True if preview_short else self.get_resolved_should_expire(),
                )
            else:
                self.log(
                    "generate_frame returned blank grid — skipping push",
                    level="DEBUG",
                )

    # ------------------------------------------------------------------
    # Frame pushing
    # ------------------------------------------------------------------

    def push_frame(
        self,
        grid: list[list[int]],
        ttl_s: Optional[int] = None,
        max_age_s: Optional[int] = None,
        override_ttl: bool = False,
        should_expire: bool = False,
        template: Optional[str] = None,
        refresh_interval_minutes: Optional[int] = None,
    ) -> None:
        """Push a frame to the controller's queue via event.

        Args:
            grid: 6x22 character grid.
            ttl_s: TTL in seconds (None = use default).
            max_age_s: Max age from creation (None = use default).
            override_ttl: Immediately display, bypassing active TTL.
            should_expire: Drop frame after TTL instead of moving to fallback.
            template: Optional template identifier for dynamic frame regeneration.
            refresh_interval_minutes: How often the controller should regenerate
                this frame using the template (None = no auto-refresh).
        """
        # Apply preview overrides if set by _handle_generate_request.
        # Preview overrides intentionally do not affect template/refresh fields —
        # a preview is always a one-shot display, not a recurring template push.
        overrides = getattr(self, "_preview_overrides", None) or {}
        if overrides:
            ttl_s = overrides.get("ttl_s", ttl_s)
            override_ttl = overrides.get("override_ttl", override_ttl)
            should_expire = overrides.get("should_expire", should_expire)

        payload: dict[str, Any] = {
            "automation_id": self.name,
            "source_label": self.display_name,
            "characters": json.dumps(grid),
            "ttl_s": ttl_s,
            "max_age_s": max_age_s,
            "override_ttl": override_ttl,
            "should_expire": should_expire,
        }
        if self._next_fire_time is not None:
            payload["next_fire_time"] = self._next_fire_time
        if template is not None:
            payload["template"] = template
        if refresh_interval_minutes is not None:
            payload["refresh_interval_minutes"] = refresh_interval_minutes

        self.fire_event(
            "vestaboard_controller_command",
            command="push_automation_frame",
            payload=json.dumps(payload),
        )
        self.log(
            f"push_frame fired for {self.name!r} | "
            f"ttl_s={ttl_s} max_age_s={max_age_s} "
            f"override_ttl={override_ttl} should_expire={should_expire}"
            + (f" template={template!r}" if template is not None else "")
            + (f" refresh_interval_minutes={refresh_interval_minutes}" if refresh_interval_minutes is not None else ""),
            level="INFO",
        )

    # ------------------------------------------------------------------
    # Config helpers
    # ------------------------------------------------------------------

    def get_effective_config(self) -> dict[str, Any]:
        """Return merged YAML args + UI config for status publishing."""
        cfg = dict(self.args or {})
        # Remove internal AppDaemon keys
        for key in ("module", "class", "dependencies", "controller_app"):
            cfg.pop(key, None)
        return cfg

    def get_resolved_ttl_s(self) -> Optional[int]:
        """Resolve TTL from config, falling back to class default."""
        cfg = self.args or {}
        ttl_minutes = cfg.get("ttl_minutes")
        if ttl_minutes is not None:
            return int(float(ttl_minutes) * 60)
        return self.default_ttl_s

    def get_resolved_should_expire(self) -> bool:
        """Resolve should_expire from config, falling back to class default."""
        cfg = self.args or {}
        return bool(cfg.get("should_expire", self.default_should_expire))

    # ------------------------------------------------------------------
    # Config schema & preview (subclasses override)
    # ------------------------------------------------------------------

    @classmethod
    def get_config_schema(cls) -> dict[str, Any]:
        """Return UI-renderable config field definitions."""
        return {}

    def get_preview_frame(self) -> list[list[int]]:
        """Return a representative 6x22 frame for preview display."""
        return [[0] * 22 for _ in range(6)]

    # ------------------------------------------------------------------
    # UI config updates from controller
    # ------------------------------------------------------------------

    def on_config_updated(self, config: dict[str, Any]) -> None:
        """Called by controller when UI config changes.

        Merges new values into self.args so automation code can read them.
        Subclasses can override for side-effects (e.g. rescheduling timers).
        """
        if not isinstance(self.args, dict):
            return
        self.args.update(config)

    def set_enabled(self, enabled: bool) -> None:
        """Called by controller to enable/disable this automation.

        Subclasses should override to start/stop their timers.
        """
        pass

    # ------------------------------------------------------------------
    # Abstract interface
    # ------------------------------------------------------------------

    @abstractmethod
    async def generate_frame(self, **kwargs) -> list[list[int]]:
        """Generate a 6x22 character grid for the current moment."""
        raise NotImplementedError

    # ------------------------------------------------------------------
    # Random interval scheduling helpers
    # ------------------------------------------------------------------

    _random_interval_handle: Any = None
    _next_fire_time: Optional[float] = None

    def _schedule_random_interval(
        self,
        callback,
        min_minutes: float = 30,
        max_minutes: float = 120,
    ) -> None:
        """Schedule a callback at a random interval within the given range.

        After the callback fires, call this again to schedule the next one.
        """
        self._cancel_random_interval()

        min_minutes = min(min_minutes, max_minutes)
        delay_s = random.uniform(float(min_minutes), float(max_minutes)) * 60
        self._next_fire_time = time.time() + delay_s

        self._random_interval_handle = self.run_in(callback, int(delay_s))

        self.log(
            f"Random interval scheduled: next fire in {delay_s / 60:.1f} min",
            level="INFO",
        )

        # Notify controller of updated next_fire_time so card shows "Upcoming"
        self._notify_next_fire_time()

    def _notify_next_fire_time(self) -> None:
        """Send next_fire_time to controller so the card shows upcoming automations."""
        try:
            self.fire_event(
                "vestaboard_controller_command",
                command="update_next_fire_time",
                payload=json.dumps({
                    "automation_id": self.name,
                    "next_fire_time": self._next_fire_time,
                }),
            )
        except Exception:
            pass

    def _clear_random_interval_handle(self) -> None:
        """Clear the handle without cancelling (use when the timer already fired)."""
        self._random_interval_handle = None
        self._next_fire_time = None

    def _cancel_random_interval(self) -> None:
        """Cancel any pending random interval timer."""
        if self._random_interval_handle is not None:
            try:
                self.cancel_timer(self._random_interval_handle)
            except Exception:
                pass
            self._random_interval_handle = None
        self._next_fire_time = None

    # ------------------------------------------------------------------
    # Helpers for fire-and-push pattern
    # ------------------------------------------------------------------

    async def _generate_and_push(self, **generate_kwargs) -> None:
        """Generate a frame and push it to the controller."""
        try:
            grid = await self.generate_frame(**generate_kwargs)
            if grid and any(any(cell != 0 for cell in row) for row in grid):
                self.push_frame(
                    grid,
                    ttl_s=self.get_resolved_ttl_s(),
                    max_age_s=self.default_max_age_s,
                    should_expire=self.get_resolved_should_expire(),
                )
            else:
                self.log("generate_frame returned blank grid — skipping push", level="DEBUG")
        except Exception as exc:
            self.log(f"generate_and_push failed: {exc!r}", level="ERROR")
