"""Base class for Vestaboard board automations."""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import TYPE_CHECKING, Any, Optional

if TYPE_CHECKING:
    pass


class BoardAutomation(ABC):
    """Abstract base for Vestaboard board automations.

    Each automation knows how to:
    - Declare what HA triggers it should listen to (via get_triggers).
    - Generate a 6x22 character grid on demand (via generate_frame).

    The controller app registers/deregisters these triggers and calls
    generate_frame() when a trigger fires, then pushes the result to the
    FrameQueue.
    """

    #: Human-readable name shown in status / logs.
    name: str = "BoardAutomation"

    #: Default TTL in seconds for frames generated by this automation.
    #: None = hold indefinitely (until another frame overrides or TTL expires).
    default_ttl_s: Optional[int] = None

    #: Default absolute expiration in seconds from frame creation time.
    #: None = no expiration.
    default_expiration_s: Optional[int] = None

    def __init__(self, app: Any, config: dict[str, Any]) -> None:
        """Initialise the automation.

        Args:
            app: Reference to the AppDaemon VestaboardControllerApp instance.
                 Used for logging, service calls, and state access.
            config: Per-automation configuration dict from apps.yaml.
        """
        self.app = app
        self.config = config

    # ------------------------------------------------------------------
    # Abstract interface
    # ------------------------------------------------------------------

    @abstractmethod
    def get_triggers(self) -> list[dict[str, Any]]:
        """Return a list of trigger configurations for this automation.

        Each trigger dict must have at least a ``type`` key:
          - ``{"type": "state", "entity_id": "...", "callback": fn}``
          - ``{"type": "time_interval", "interval_s": 60, "callback": fn}``

        The controller app interprets these and registers the corresponding
        AppDaemon listeners.
        """
        raise NotImplementedError

    @abstractmethod
    async def generate_frame(self) -> list[list[int]]:
        """Generate a 6x22 character grid for the current moment.

        Returns:
            A 6-row x 22-column list of Vestaboard integer character codes.
        """
        raise NotImplementedError

    # ------------------------------------------------------------------
    # Helpers available to subclasses
    # ------------------------------------------------------------------

    def log(self, message: str, level: str = "INFO") -> None:
        """Delegate to the AppDaemon app's logger."""
        self.app.log(f"[{self.name}] {message}", level=level)
