"""Base class for Vestaboard board automations."""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import TYPE_CHECKING, Any, Optional

if TYPE_CHECKING:
    pass


class BoardAutomation(ABC):
    """Abstract base for Vestaboard board automations.

    Each automation knows how to:
    - Declare what HA triggers it should listen to (via get_triggers).
    - Generate a 6x22 character grid on demand (via generate_frame).

    The controller app registers/deregisters these triggers and calls
    generate_frame() when a trigger fires, then pushes the result to the
    FrameQueue.
    """

    #: Human-readable name shown in status / logs.
    name: str = "BoardAutomation"

    #: Short description shown in the store UI.
    description: str = "A Vestaboard automation."

    #: Default TTL in seconds for frames generated by this automation.
    #: None = hold indefinitely (until another frame overrides or TTL expires).
    default_ttl_s: Optional[int] = None

    #: Default max age in seconds from frame creation time (dropped from queue if stale).
    #: None = no expiration.
    default_max_age_s: Optional[int] = None

    #: Whether frames from this automation should expire by default.
    default_should_expire: bool = False

    #: Default UI-editable configuration for this automation.
    #: Subclasses should override with their specific config fields.
    DEFAULT_UI_CONFIG: dict[str, Any] = {}

    def __init__(self, app: Any, config: dict[str, Any]) -> None:
        """Initialise the automation.

        Args:
            app: Reference to the AppDaemon VestaboardControllerApp instance.
                 Used for logging, service calls, and state access.
            config: Per-automation configuration dict from apps.yaml.
        """
        self.app = app
        self.config = config

        #: Next scheduled fire time (unix timestamp), for status display.
        self.next_fire_time: Optional[float] = None

    # ------------------------------------------------------------------
    # Config schema & preview
    # ------------------------------------------------------------------

    @classmethod
    def get_config_schema(cls) -> dict[str, Any]:
        """Return UI-renderable config field definitions.

        Each key is a config field name, value is a dict with at least
        ``type`` (str, int, float, bool) and optionally ``label``,
        ``min``, ``max``, ``default``.

        Override in subclasses. Returns empty dict by default.
        """
        return {}

    def get_preview_frame(self) -> list[list[int]]:
        """Return a representative 6x22 frame for preview display.

        Returns a blank frame by default. Subclasses may override.
        """
        return [[0] * 22 for _ in range(6)]

    # ------------------------------------------------------------------
    # Abstract interface
    # ------------------------------------------------------------------

    @abstractmethod
    def get_triggers(self) -> list[dict[str, Any]]:
        """Return a list of trigger configurations for this automation.

        Each trigger dict must have at least a ``type`` key:
          - ``{"type": "state", "entity_id": "...", "callback": fn}``
          - ``{"type": "time_interval", "interval_s": 60, "callback": fn}``

        The controller app interprets these and registers the corresponding
        AppDaemon listeners.
        """
        raise NotImplementedError

    @abstractmethod
    async def generate_frame(self) -> list[list[int]]:
        """Generate a 6x22 character grid for the current moment.

        Returns:
            A 6-row x 22-column list of Vestaboard integer character codes.
        """
        raise NotImplementedError

    # ------------------------------------------------------------------
    # Helpers available to subclasses
    # ------------------------------------------------------------------

    def log(self, message: str, level: str = "INFO") -> None:
        """Delegate to the AppDaemon app's logger."""
        self.app.log(f"[{self.name}] {message}", level=level)
