alias: "[Light] [ZSE41] : [Primary Closet] : [Door Open] : [Turn On]"
description: ""
trigger:
  - platform: state
    entity_id: binary_sensor.upstairs_primary_closet_open_closed_sensor_open
    from: null
    to: "on"
condition: []
action:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.upstairs_primary_closet_lights
mode: single
