alias: "[Switch] : [Back Yard] : [Slider Opens] : [Turn On Spotlight]"
description: ""
mode: single
trigger:
  - platform: device
    type: opened
    device_id: 548726b7acac331d3495a5474991d5f7
    entity_id: binary_sensor.kitchen_slider_usl_entry_contact
    domain: binary_sensor
condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
action:
  - action: light.turn_on
    target:
      entity_id: light.downstairs_kitchen_back_yard_spotlight
    data: {}
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - if:
      - condition: state
        entity_id: binary_sensor.backyard_all_clear
        state:
          - "on"
    then:
      - action: light.turn_off
        target:
          entity_id: light.downstairs_kitchen_back_yard_spotlight
        data: {}
