alias: "[Light] [Inovelli] : [Movie Room] : [Motion Cleared] : [Lights Off]"
description: >
  Movie room is OFF-only: we don't auto-turn on lights here; we only ensure
  lights turn off after the room is empty.
triggers:
  - trigger: template
    value_template: |
      {{
        is_state('binary_sensor.basement_movie_inovelli_presence_occupancy', 'off')
        and is_state('binary_sensor.basement_rumpus_room_aqara_fp2_01_presence_sensor', 'off')
      }}
conditions: []
actions:
  - condition: template
    value_template: |
      {# Only run when hold is clear #}
      {% set s = 'basement_movie_inovelli_presence' %}
      {% set manual = states('input_text.inovelli_manual_hold') | int(85) %}
      {% set auto = states('input_text.inovelli_auto_hold') | int(0) %}
      {% set led1 = states('number.' ~ s ~ '_defaultled1colorwhenon') | int(-1) %}
      {{ led1 != manual and led1 != auto }}
  - delay: >-
      {% set raw = states('input_select.basement_movie_room_occupancy_off_delay') %}
      {% set d = raw | replace('"','') | replace("'","") | trim %}
      {{ d if d not in ['unknown','unavailable',''] else '00:05:00' }}
  - condition: template
    value_template: |
      {{
        is_state('binary_sensor.basement_movie_inovelli_presence_occupancy', 'off')
        and is_state('binary_sensor.basement_rumpus_room_aqara_fp2_01_presence_sensor', 'off')
      }}
  - condition: template
    value_template: |
      {# Re-check hold state after the delay #}
      {% set s = 'basement_movie_inovelli_presence' %}
      {% set manual = states('input_text.inovelli_manual_hold') | int(85) %}
      {% set auto = states('input_text.inovelli_auto_hold') | int(0) %}
      {% set led1 = states('number.' ~ s ~ '_defaultled1colorwhenon') | int(-1) %}
      {{ led1 != manual and led1 != auto }}
  - action: light.turn_off
    target:
      entity_id:
        - light.basement_movie_room_lights
        - light.basement_movie_room_ambient_lighting
mode: restart
