alias: "[Light] [ZSE11] : [Basement Hallway] : [Motion Detected] : [Lights On]"
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.basement_hallway_qsensor_motion_detection
      - binary_sensor.basement_hallway_inovelli_presence_occupancy
    from: null
    to: "on"
conditions:
  - alias: Skip when the hallway switch is on manual or auto hold
    condition: template
    value_template: |
      {# Only run when hold is clear #}
      {% set s = 'basement_hallway_inovelli_presence' %}
      {% set manual = states('input_text.inovelli_manual_hold') | int(85) %}
      {% set auto = states('input_text.inovelli_auto_hold') | int(0) %}
      {% set led1 = states('number.' ~ s ~ '_defaultled1colorwhenon') | int(-1) %}
      {{ led1 != manual and led1 != auto }}
actions:
  - action: light.turn_on
    metadata: {}
    data:
      color_temp_kelvin: 2750
      brightness_pct: 100
    target:
      entity_id: light.basement_hall_lights
mode: single
